{"timestamp":"2025-07-03T19:18:20.900249","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-07-03T19:18:20.901035","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/basicDag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-07-03T19:18:21.218819","level":"info","event":"Spinning up container for /home/airflow/tropo-objects/example-tropo-2.rtf","logger":"root"}
{"timestamp":"2025-07-03T19:18:21.621637","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"APIError","exc_value":"409 Client Error for http+docker://localhost/v1.49/containers/create?name=spinup_worker_1751570301: Conflict (\"Conflict. The container name \"/spinup_worker_1751570301\" is already in use by container \"555368608fb821da3159e371dc70c549fedae102ff4a6e364d99e493042b1813\". You have to remove (or rename) that container to be able to reuse that name.\")","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/basicDag.py","lineno":168,"name":"spinup_workers"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/models/containers.py","lineno":876,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/models/containers.py","lineno":935,"name":"create"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py","lineno":440,"name":"create_container"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/container.py","lineno":457,"name":"create_container_from_config"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py","lineno":281,"name":"_result"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py","lineno":277,"name":"_raise_for_status"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/errors.py","lineno":39,"name":"create_api_error_from_http_exception"}],"is_group":false,"exceptions":[]},{"exc_type":"HTTPError","exc_value":"409 Client Error: Conflict for url: http+docker://localhost/v1.49/containers/create?name=spinup_worker_1751570301","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/docker/api/client.py","lineno":275,"name":"_raise_for_status"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/models.py","lineno":1024,"name":"raise_for_status"}],"is_group":false,"exceptions":[]}]}
